### ISSUE TITLE
[Help] Help with an particular cadence sensor

### ISSUE THREAD

**Issue by ebellumat** [amcolash/oled-bike-computer#2]
Hello Andrew,

My name is Erasmo, I'm a developer, I need some help with a bluetooth device.

https://www.amazon.com/MEILAN-Wireless-Bluetooth-Computer-Waterproof/dp/B07QCPLVFC

I connect to him but I can't parse the retrieved data from this little device.

I read your repository "oled-bike-computer" but my device doesn't have Uint32Array, they have only Int8Array and Uint8Array data.

Can you help me with this?

Regards, Erasmo.

![image](https://user-images.githubusercontent.com/26942680/92274101-fb92f600-eec2-11ea-862f-caf62a5cd46d.png)
![image](https://user-images.githubusercontent.com/26942680/92274137-09e11200-eec3-11ea-9423-61beb19c629b.png)

**Comment by amcolash** [comment]
Unfortunately, I don't have too much knowledge on how different sensors work and this repo is shared to the public as an example and backup. You're free to share MRs, but I don't currently have time to take a look. Here are some possible resources that might be useful:

https://www.bluetooth.com/blog/the-wheels-on-the-bike-are-bluetooth-smart-bluetooth-smart-bluetooth-smart/
https://learn.adafruit.com/bluetooth-bicycle-speed-cadence-sensor-display-with-clue
